// <auto-generated />
namespace CreepySuits.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lala988097658768760987879988898736278930493821902340t48392039483998u5294tu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lala988097658768760987879988898736278930493821902340t48392039483998u5294tu));
        
        string IMigrationMetadata.Id
        {
            get { return "201811111104162_lala98809765876876098787998889873627893049382190-2340t4839-2039483998u52-94tu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
